### ISSUE TITLE
无法下载封面图，emby一直转圈

### ISSUE THREAD

**Issue by bigwenoopsie** [javtube/jellyfin-plugin-javtube#24]
日志如下：

2022-07-01 14:51:45.039 Info Server: http/1.1 POST http://host1/emby/Items/19007/RemoteImages/Download?Type=Primary&ImageUrl=https://javtube-bigwen.herokuapp.com:443/v1/images/primary/10musume/082215_01?url=&pos=-1&auto=False&ProviderName=JavTube&X-Emby-Client=Emby Web&X-Emby-Device-Name=Safari macOS&X-Emby-Device-Id=c75b2e88-f89a-49be-971e-5be36762a20a&X-Emby-Client-Version=4.7.4.0. UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15
2022-07-01 14:51:45.040 Info HttpClient: GET https://javtube-bigwen.herokuapp.com:443/v1/images/primary/10musume/082215_01?url=&pos=-1&auto=False
2022-07-01 14:51:45.821 Error Server: Error processing request
	*** Error Report ***
	Version: 4.7.4.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 5.4.0-121-generic (buildd@lcy02-amd64-013) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)) #137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2
	Framework: .NET 6.0.2
	OS/Process: x64/x64
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /config
	Application path: /system
	MediaBrowser.Model.Net.HttpException: MediaBrowser.Model.Net.HttpException: NotFound
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.(HttpRequestOptions , String )
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
	   at Emby.Providers.Manager.ProviderManager.SaveImageFromRemoteUrl(BaseItem item, LibraryOptions libraryOptions, String url, ImageType type, Nullable`1 imageIndex, Boolean isFallbackImage, CancellationToken cancellationToken)
	   at Emby.Api.Images.RemoteImageService.DownloadRemoteImage(BaseItem item, BaseDownloadRemoteImage request)
	   at Emby.Server.Implementations.Services.ServiceController.(Task )
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: Emby.Server.Implementations
	TargetSite: Void ()
	
2022-07-01 14:51:45.823 Info Server: http/1.1 Response 500 to host2. Time: 784ms. http://host1/emby/Items/19007/RemoteImages/Download?Type=Primary&ImageUrl=https://javtube-bigwen.herokuapp.com:443/v1/images/primary/10musume/082215_01?url=&pos=-1&auto=False&ProviderName=JavTube&X-Emby-Client=Emby Web&X-Emby-Device-Name=Safari macOS&X-Emby-Device-Id=c75b2e88-f89a-49be-971e-5be36762a20a&X-Emby-Client-Version=4.7.4.0

**Comment by bigwenoopsie** [comment]
> [`https://www.10musume.com/movies/082215_01/`](https://www.10musume.com/movies/082215_01/)
> 
> 这部在官网被下架了，所以404没有封面图了。换个刮削源就行了。

Javtube的插件设置里没有看到刮削源的设置选项？

**Comment by xjasonlyu** [comment]
数量不多的话手动识别一下就行了。
