### ISSUE TITLE
[Feature] 建议为FC2网站添加备用源

### ISSUE THREAD

**Issue by kmou424** [javtube/jellyfin-plugin-javtube#41]
### Description

FC2官网经常出现卖家删除商品，但是视频本身已经流出的情况，这种情况下这类视频就无法从FC2官网获取到元数据和封面（比如FC2-1757248，这类的还有很多），建议添加一个备用的第三方源，如果无法从官网获取到，就从第三方源获取

### Do you have a specific solution in mind?

建议使用 https://fc2hub.com 作为第三方源

**Comment by kkh66** [comment]
赞成

**Comment by chenyao8954** [comment]
赞成，希望能够麻烦作者加上这个源，现在近一半的fc2资源无法刮削（心塞）

**Comment by NegroniBlanco** [comment]
bump. we need fallback options

**Comment by xjasonlyu** [comment]
fc2hub已支持

**Comment by NegroniBlanco** [comment]
> fc2hub已支持

感谢您的回复（当然还有很棒的插件）

不知道它已经实现了，因为 fc2hub 后备无法正常工作。

例如，插件无法获取有关 FC2-1027978 的信息并返回错误消息。
jellyfin log:
```
[ERR] [23] MediaBrowser.Providers.Movies.MovieMetadataService: Error in JavTube
System.Exception: API request error: 404 (info not found)
   at Jellyfin.Plugin.JavTube.ApiClient.GetDataAsync[T](String url, Boolean requireAuth, CancellationToken cancellationToken)
   at Jellyfin.Plugin.JavTube.ApiClient.SearchMovieAsync(String q, String provider, Boolean fallback, CancellationToken cancellationToken)
   at Jellyfin.Plugin.JavTube.ApiClient.SearchMovieAsync(String q, String provider, CancellationToken cancellationToken)
   at Jellyfin.Plugin.JavTube.Providers.MovieProvider.GetSearchResults(MovieInfo info, CancellationToken cancellationToken)
   at Jellyfin.Plugin.JavTube.Providers.MovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

backewnd log:
```
2022-10-05T05:34:35.112684+00:00 app[web.1]: [GORM] 2022/10/05 05:34:35 github.com/javtube/javtube-sdk-go/engine/movie.go:173 record not found
2022-10-05T05:34:35.112696+00:00 app[web.1]: [0.856ms] [rows:0] SELECT * FROM `movie_metadata` WHERE provider = "FC2" AND id = "1027978" COLLATE NOCASE ORDER BY `movie_metadata`.`id` LIMIT 1
2022-10-05T05:34:35.754491+00:00 app[web.1]: [GORM] 2022/10/05 05:34:35 github.com/javtube/javtube-sdk-go/engine/movie.go:24
2022-10-05T05:34:35.754514+00:00 app[web.1]: [0.233ms] [rows:0] SELECT * FROM `movie_metadata` WHERE number = "FC2-1027978" COLLATE NOCASE OR id = "FC2-1027978" COLLATE NOCASE
2022-10-05T05:34:35.754547+00:00 app[web.1]: [GIN] 2022/10/05 - 05:34:35 | 404 |  644.506792ms |   {jellyfin_ip} | GET      "/v1/movies/search?q=FC2-1027978&provider=&fallback=True"
2022-10-05T05:34:35.759502+00:00 heroku[router]: at=info method=GET path="/v1/movies/search?q=FC2-1027978&provider=&fallback=True" host=someaddress.herokuapp.com request_id=cdec1f76-cb4a-4f2f-9729-113c42cff31e fwd="{jellyfin_ip}" dyno=web.1 connect=0ms service=646ms status=404 bytes=198 protocol=https
```

自动扫描和手动扫描都失败了，但是你可以从 fc2hub 找到信息没有问题。
https://fc2hub.com/video/305805/id1027978

环境
插件和后端都是最新的。
插件：2022.920.850.0
后端：1.0.19 (commit: e279cda, heroku）

**Comment by xjasonlyu** [comment]
你的后端版本太低，升级到1.0.21就行了。

**Comment by NegroniBlanco** [comment]
> 你的后端版本太低，升级到1.0.21就行了。

更新了后端，现在它工作得很好！ 谢谢！
