### ISSUE TITLE
[Bug] The plugin fails to retrieve any search result using the latest server container.

### ISSUE THREAD

**Issue by jj99889** [javtube/jellyfin-plugin-javtube#6]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### Version

Latest

### Description

The plugin fails to retrieve any search result due to a JSON failure that has not been witnessed in previous versions of the server container. The error message is attached below. 

```
[2022-06-07 00:55:03.528 +01:00] [ERR] [81] MediaBrowser.Providers.Manager.ProviderManager: Provider "JavTube" failed to retrieve search results
System.Text.Json.JsonException: The JSON value could not be converted to System.Collections.Generic.List`1[Jellyfin.Plugin.JavTube.Models.MovieSearchResultModel]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.ReadAll[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo)
   at Jellyfin.Plugin.JavTube.ApiClient.GetDataFromApi[T](String url, CancellationToken cancellationToken)
   at Jellyfin.Plugin.JavTube.ApiClient.SearchMovie(String keyword, String provider, Boolean lazy, CancellationToken cancellationToken)
   at Jellyfin.Plugin.JavTube.ApiClient.SearchMovie(String keyword, String provider, CancellationToken cancellationToken)
   at Jellyfin.Plugin.JavTube.Providers.MovieProvider.GetSearchResults(MovieInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
```

### Jellyfin/Emby Logs

[2022-06-07 00:55:03.528 +01:00] [ERR] [81] MediaBrowser.Providers.Manager.ProviderManager: Provider "JavTube" failed to retrieve search results
System.Text.Json.JsonException: The JSON value could not be converted to System.Collections.Generic.List`1[Jellyfin.Plugin.JavTube.Models.MovieSearchResultModel]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.ReadAll[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo)
   at Jellyfin.Plugin.JavTube.ApiClient.GetDataFromApi[T](String url, CancellationToken cancellationToken)
   at Jellyfin.Plugin.JavTube.ApiClient.SearchMovie(String keyword, String provider, Boolean lazy, CancellationToken cancellationToken)
   at Jellyfin.Plugin.JavTube.ApiClient.SearchMovie(String keyword, String provider, CancellationToken cancellationToken)
   at Jellyfin.Plugin.JavTube.Providers.MovieProvider.GetSearchResults(MovieInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)

### JavTube Server Logs

The server side is actually working fine as indicated below where correct results are being returned to the client-side plugin.

[GIN] 2022/06/06 - 23:52:35 | 200 |  1.566801791s |    54.86.50.139 | GET      "/api/search/movie?keyword=[Redacted]"
[GIN] 2022/06/06 - 23:55:03 | 200 |  3.385909012s |  109.175.189.33 | GET      "/api/search/movie?keyword=[Redacted]"

**Comment by jj99889** [comment]
I imagine the response deserialization should be changed to reflect the latest development of the server?

**Comment by xjasonlyu** [comment]
that’s as expected, the plugin will be updated soon to support newest api backend server.

**Comment by jj99889** [comment]
Then, I would suggest you to label the server container so that it would be easier to know which version corresponds to which plugin.

**Comment by xjasonlyu** [comment]
I will label images when first stable version is released.

**Comment by jj99889** [comment]
Then, which version of the image do you suggest I use with the plugin? Thanks!

**Comment by xjasonlyu** [comment]
wait until I release the new plugin with the newest api endpoints support.
