### ISSUE TITLE
[Bug] API request error: 404 (info not found) 导致每次扫库都会重新刮削其中一些文件非常慢

### ISSUE THREAD

**Issue by kuroyukihime0** [javtube/jellyfin-plugin-javtube#61]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/javtube/jellyfin-plugin-javtube/wiki), especially the [FAQ](https://github.com/javtube/jellyfin-plugin-javtube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### JavTube Plugin Version

v2022.905.1521.0

### JavTube Server Version

1.0.14

### What OS are you seeing the problem on?

Other

### Description

刮削一些特定文件时候失败，导致没有入库（？），每次重新扫库都会重新刮这些文件，导致十分缓慢

可复现文件名：FC2-1723477 FC2-1957744等

### Jellyfin/Emby Logs

2022-09-15 12:45:02.895 Error App: Error in JavTube
	*** Error Report ***
	Version: 4.7.6.0
	Command line: /volume1/@appstore/EmbyServer/system/EmbyServer.dll -programdata /volume1/Emby -ffdetect /var/packages/EmbyServer/target/bin/ffdetect -ffmpeg /var/packages/EmbyServer/target/bin/ffmpeg -ffprobe /var/packages/EmbyServer/target/bin/ffprobe -nolocalportconfig -ignore_vaapi_enabled_flag -pidfile /volume1/Emby/EmbyServer.pid -defaultdirectory /volume1/Public -updatepackage emby-server-synology_{version}_x86_64.spk -noautorunwebapp
	Operating system: Linux version 3.10.105 (root@build3) (gcc version 4.9.3 20150311 (prerelease) (crosstool-NG 1.20.0) ) #25426 SMP Mon Dec 14 18:47:46 CST 2020
	Framework: .NET 6.0.2
	OS/Process: x64/x64
	Runtime: volume1/@appstore/EmbyServer/system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /volume1/Emby
	Application path: /volume1/@appstore/EmbyServer/system
	System.Exception: System.Exception: API request error: 404 (info not found)
	   at Jellyfin.Plugin.JavTube.ApiClient.GetDataAsync[T](String url, Boolean requireAuth, CancellationToken cancellationToken)
	   at Jellyfin.Plugin.JavTube.ApiClient.SearchMovieAsync(String q, String provider, Boolean fallback, CancellationToken cancellationToken)
	   at Jellyfin.Plugin.JavTube.ApiClient.SearchMovieAsync(String q, String provider, CancellationToken cancellationToken)
	   at Jellyfin.Plugin.JavTube.Providers.MovieProvider.GetSearchResults(MovieInfo info, CancellationToken cancellationToken)
	   at Jellyfin.Plugin.JavTube.Providers.MovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
	   at Emby.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, LibraryOptions libraryOptions, String logName, TIdType id, IEnumerable`1 providers, MetadataRefreshOptions options, CancellationToken cancellationToken)
	Source: JavTube
	TargetSite: Void MoveNext()
	

### JavTube Server Logs

<html>
<body>

2022-09-15 04:45:02 | stdout | [GIN] 2022/09/15 - 04:45:02 \| 404 \|  4.793767158s \|  192.168.50.100 \| GET      "/v1/movies/search?q=FC2-1723477+%E3%80%90%E6%9C%9F%E9%97%B4%E9%99%90%E5%AE%9A%E3%82%BB%E3%83%BC%E3%83%AB%E4%B8%AD%E3%80%91%E3%81%86%E3%81%A9%E3%82%93%E3%81%92%E3%81%A1%E3%82%83%E3%82%93%E3%81%AF%E5%B1%A5%E3%81%84%E3%81%A6%E3%81%BE%E3%81%9B%E3%82%93%EF%BC%81%E6%B7%AB%E4%B9%B1%E3%81%86%E3%81%95%E3%81%8E%E3%81%AB2%E7%99%BA%E5%B0%84%E3%82%A4%E3%83%A9%E3%83%9E%EF%BC%86%E7%94%9F%E4%B8%AD%E5%87%BA%E3%81%97%EF%BC%86%E5%B0%BB%E3%81%B6%E3%81%A3%E3%81%8B%E3%81%91%EF%BC%81&provider=&fallback=True"
-- | -- | --
2022-09-15 04:45:02 | stdout | [6.223ms] [rows:0] SELECT * FROM `movie_metadata` WHERE number = "FC2-1723477" COLLATE NOCASE OR id = "FC2-1723477" COLLATE NOCASE
2022-09-15 04:45:02 | stdout | [GORM] 2022/09/15 04:45:02 github.com/javtube/javtube-sdk-go/engine/movie.go:24
2022-09-15 04:44:58 | stdout | [1.201ms] [rows:0] SELECT * FROM `movie_metadata` WHERE provider = "FC2" AND id = "1723477" COLLATE NOCASE ORDER BY `movie_metadata`.`id` LIMIT 1
2022-09-15 04:44:58 | stdout | [GORM] 2022/09/15 04:44:58 github.com/javtube/javtube-sdk-go/engine/movie.go:173 record not found

</body>
</html>

### How to Reproduce

可复现文件名：FC2-1723477 FC2-1957744等

**Comment by xjasonlyu** [comment]
如果有部分影片没有刮削出来，例如FC2，下次扫描时emby确实会尝试重新刮削，现在看来最好的方法还是手动补全一下元数据。

**Comment by kuroyukihime0** [comment]
> 如果有部分影片没有刮削出来，例如FC2，下次扫描时emby确实会尝试重新刮削，现在看来最好的方法还是手动补全一下元数据。

我把刮削器停了重刷一次库暂时解决了，其他刮削器好像不会出现这个失败重新刮削的情况

然后这几个报错的文件也是有对应的其他软件生成nfo文件的， 请问是缺少了哪些部分导致会一直重复刮么？

**Comment by xjasonlyu** [comment]
那应该就不是插件的问题了，有nfo自然会优先使用nfo数据的。

**Comment by kuroyukihime0** [comment]
> 那应该就不是插件的问题了，有nfo自然会优先使用nfo数据的。

好的感谢

**Comment by Yzzzed** [comment]
> > 如果有部分影片没有刮削出来，例如FC2，下次扫描时emby确实会尝试重新刮削，现在看来最好的方法还是手动补全一下元数据。
> 
> 我把刮削器停了重刷一次库暂时解决了，其他刮削器好像不会出现这个失败重新刮削的情况
> 
> 然后这几个报错的文件也是有对应的其他软件生成nfo文件的， 请问是缺少了哪些部分导致会一直重复刮么？

请问是把插件禁用了然后重新扫描一遍媒体库吗 需不需要把生成的nfo文件都删了 我目前是也是报这个404的错误 然后刮削的数据只有一些片段截图 海报头像简介啥的都没有
