### ISSUE TITLE
[Bug] 演员图片获取url生成错误

### ISSUE THREAD

**Issue by TanY0Y0** [javtube/jellyfin-plugin-javtube#62]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/javtube/jellyfin-plugin-javtube/wiki), especially the [FAQ](https://github.com/javtube/jellyfin-plugin-javtube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### JavTube Plugin Version

v2022.905.1521.0

### JavTube Server Version

1.0.14

### What OS are you seeing the problem on?

Linux

### Description

在请求gfriend图片时，在合成url时“https://raw.githubusercontent.com/gfriends/gfriends/master/Content/5-Ebody/%E5%B8%82%E5%8E%9F%E7%8E%B2.jpg%3Ft=1629184014”，其中url无法识别“%3Ft=1629184014“，把%3F改成?后可以解析
在手动识别演员时的url同样存在问题

### Jellyfin/Emby Logs

[2022-09-15 20:56:24.880 +08:00] [WRN] [49] Emby.Server.Implementations.Library.LibraryManager: Cannot fetch image from "https://raw.githubusercontent.com/gfriends/gfriends/master/Content/5-Ebody/%E5%B8%82%E5%8E%9F%E7%8E%B2.jpg%3Ft=1629184014"
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)

[2022-09-15 21:09:29.222 +08:00] [WRN] [44] Emby.Server.Implementations.Library.LibraryManager: Cannot fetch image from "http://xxx.xxx.xxx.xxx:xxxx/v1/images/primary/XsList/160180?url=https%3a%2f%2fraw.githubusercontent.com%2fgfriends%2fgfriends%2fmaster%2fContent%2f1-FALENO%2f%25E7%25B6%25BF%25E8%25B2%25AB%25E3%2581%2593%25E3%2582%2588%25E3%2581%25BF.jpg%253Ft%3d1654902510&ratio=-1&pos=0.5&auto=True"
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)

### How to Reproduce

自动或手动刮削影片或演员，报错

**Comment by xjasonlyu** [comment]
是的，一小时前gfriends刚更新加了这个时间戳`t`，下个版本会修复这个问题。
