### ISSUE TITLE
[Bug] emby 4.7.4.0 今天突然发现刮削搜索失败，之前还可以。

### ISSUE THREAD

**Issue by 2229614420** [javtube/jellyfin-plugin-javtube#68]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/javtube/jellyfin-plugin-javtube/wiki), especially the [FAQ](https://github.com/javtube/jellyfin-plugin-javtube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### JavTube Plugin Version

2022.920.850.0

### JavTube Server Version

1.0.18

### Description

刮削搜索失败，日志报错。

### Jellyfin/Emby Logs

2022-09-24 14:15:56.203 Info JavTube.MovieProvider: Search for movie: HND-723-C
2022-09-24 14:16:27.476 Error ProviderManager: Error searching
*** Error Report ***
Version: 4.7.4.0
Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
Operating system: Linux version 4.4.59+ (root@build3) (gcc version 4.9.3 20150311 (prerelease) (crosstool-NG 1.20.0) ) #25426 SMP PREEMPT Tue May 12 04:54:55 CST 2020
Framework: .NET 6.0.2
OS/Process: x64/x64
Runtime: system/System.Private.CoreLib.dll
Processor count: 4
Data path: /config
Application path: /system
System.Text.Json.JsonException: System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
at System.Text.Json.Utf8JsonReader.Read()
at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
--- End of inner exception stack trace ---
at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)

### JavTube Server Logs

022-09-24T06:16:57.367847+00:00 app[web.1]: [GORM] 2022/09/24 06:16:57 github.com/javtube/javtube-sdk-go/engine/movie.go:24
2022-09-24T06:16:57.367856+00:00 app[web.1]: [0.239ms] [rows:0] SELECT * FROM `movie_metadata` WHERE number = "HND-723" COLLATE NOCASE OR id = "HND-723" COLLATE NOCASE
2022-09-24T06:16:57.367954+00:00 app[web.1]: [GIN] 2022/09/24 - 06:16:57 | 200 |          1m0s |    50.7.158.186 | GET      "/v1/movies/search?q=HND-723-C&provider=&fallback=True"

**Comment by xjasonlyu** [comment]
应该是你的搭建平台，可能是云平台服务问题。这是heroku吗，大概服务到期了？

**Comment by segaxy** [comment]
后端更新下试试
