### ISSUE TITLE
[Feature] 检索元数据错误

### ISSUE THREAD

**Issue by jkmiku** [javtube/jellyfin-plugin-javtube#74]
EMBY版本：4.7.5.0
部署系统：UNRAID 6.10.3 
EMBY插件设置：
![image](https://user-images.githubusercontent.com/16489571/193656949-898f64fc-f035-48ac-aace-1a95cbfb5064.png)

后端部署设置：
![image](https://user-images.githubusercontent.com/16489571/193656760-854da8b7-4fc4-40cf-8ea9-450106d9ddfd.png)

emby日志：
2022-10-03 18:48:58.062 Info JavTube.MovieProvider: Search for movie: FC2-PPV-3087371
2022-10-03 18:48:58.246 Error ProviderManager: Error searching
	*** Error Report ***
	Version: 4.7.5.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 5.15.46-Unraid (root@Develop) (gcc (GCC) 11.2.0, GNU ld version 2.37-slack15) #1 SMP Fri Jun 10 11:08:41 PDT 2022
	Framework: .NET 6.0.2
	OS/Process: x64/x64
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /config
	Application path: /system
	System.Text.Json.JsonException: System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
	 ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
	   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
	   at System.Text.Json.Utf8JsonReader.Read()
	   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
	   --- End of inner exception stack trace ---
	   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
	   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
	   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
	   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
	   at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
	   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, Encoding sourceEncoding, JsonSerializerOptions options, CancellationToken cancellationToken)
	   at Jellyfin.Plugin.JavTube.ApiClient.GetDataAsync[T](String url, Boolean requireAuth, CancellationToken cancellationToken)
	   at Jellyfin.Plugin.JavTube.ApiClient.SearchMovieAsync(String q, String provider, Boolean fallback, CancellationToken cancellationToken)
	   at Jellyfin.Plugin.JavTube.ApiClient.SearchMovieAsync(String q, String provider, CancellationToken cancellationToken)
	   at Jellyfin.Plugin.JavTube.Providers.MovieProvider.GetSearchResults(MovieInfo info, CancellationToken cancellationToken)
	   at Emby.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationToken cancellationToken)
	   at Emby.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
	Source: System.Text.Json
	TargetSite: Void ReThrowWithPath(System.Text.Json.ReadStack ByRef, System.Text.Json.JsonReaderException)
	InnerException: System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
	Source: System.Text.Json
	TargetSite: Void ThrowJsonReaderException(System.Text.Json.Utf8JsonReader ByRef, System.Text.Json.ExceptionResource, Byte, System.ReadOnlySpan`1[System.Byte])
	   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
	   at System.Text.Json.Utf8JsonReader.Read()
	   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)

**Comment by xjasonlyu** [comment]
你是想添加什么feature？
